안녕하세요. 파이토치에 오신것을 환영합니다. [사이트](https://medium.com/nlplanet/quick-intro-to-pytorch-with-examples-tensor-operations-73298d20c38a)에 있는 글을 정리하면서 실습합니다.

# What is `PyTorch`
PyTorch는 torch라이브러리를 기반으로 하는 오픈소스 ML 프레임워크
- Numpy, SciPy, Cython 같은 라이브러리와 통합
- CPU, GPU, 병렬 처리 및 분산훈련 지원
- Tensorboard로 쉽게 공유할 수 있음
- 다른 ML 프레임워크를 걸쳐 신경망을 저장하고 로드하는 형식인 ONNX(Open Neural Network Exchange) 지원

기본 연산단위는 `tensor`이고 이는 numpy와 비슷하다.

### 텐서 정의

In [7]:
import torch
import numpy as np

In [8]:
# list to tensor
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

# numpy array to tensor
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

# x_data form을 따르는 one, rand tensor
x_ones = torch.ones_like(x_data) 
x_rand = torch.rand_like(x_data, dtype=torch.float) 

print(f"x_data: \n {x_data} \n")
print(f"x_np: \n {x_np} \n")
print(f"Ones Tensor: \n {x_ones} \n")
print(f"Random Tensor: \n {x_rand} \n")
x_data == x_np

x_data: 
 tensor([[1, 2],
        [3, 4]]) 

x_np: 
 tensor([[1, 2],
        [3, 4]]) 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1319, 0.1469],
        [0.4368, 0.3176]]) 



tensor([[True, True],
        [True, True]])

In [9]:
# shape으로 tensor를 만들어보겠습니다.
shape = (2,3,)   # (2,3)이라고 적어도 되는데 (2,3,)으로 적는 것은 특별한 이유가 있는 것일까?
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1431, 0.1129, 0.8076],
        [0.5432, 0.4713, 0.1614]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 텐서 특징

`tensor`의 가장 중요한 특징은 CPU나 GPU같은 accelerator를 설정하는 `device`와 `shape`, `dtype`이 있다.

In [10]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape, tensor.size()}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: (torch.Size([3, 4]), torch.Size([3, 4]))
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### tensor를 GPU로 옮겨보겠습니다.

In [14]:
# 새로 tensor를 정의하지 않고 윗선에서 정의한 텐서를 그대로 사용하겠습니다
# GPU 사용가능하다면 텐서를 옮겨줄래~?
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


### 텐서 조작

In [23]:
# tensor indexing
tensor = torch.ones(4, 5)

print(f"tensor: \n{tensor}\n")
print(f"First row: \n{tensor[0]}\n")
print(f"First column: \n{tensor[:, 0]}\n")
print(f"Last column: \n{tensor[:, -1]}\n\n")


tensor[:,1] = 0    # 두번째 colmun을 0으로
print(f"updated tensor:\n {tensor}")

tensor: 
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

First row: 
tensor([1., 1., 1., 1., 1.])

First column: 
tensor([1., 1., 1., 1.])

Last column: 
tensor([1., 1., 1., 1.])


updated tensor:
 tensor([[1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.]])


In [26]:
# tensor concatenation
tensor = torch.ones(4, 5)
t1 = torch.cat([tensor, tensor], dim=1)
print(t1)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [27]:
# transpose와 행렬곱(matrix multiplication)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(y1)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])


In [28]:
# 연산별(Element-wise) 곱셈
z1 = tensor * tensor
z2 = tensor.mul(tensor)
print(z1)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


## PyTorch 와 Numpy를 비교해보겠습니다.

In [29]:
# Numpy CPU
size = 1000
x = np.random.normal(size=(size, size)).astype(np.float32)
%timeit np.dot(x, x.T)

11.9 ms ± 1.51 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [30]:
# PyTorch CPU
size = 1000
x = torch.rand(size=(size, size), dtype=torch.float32)
%timeit x @ x.T

# Pytorch CPU를 사용하는 것이 조금 더 느리다

15.2 ms ± 2.05 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [33]:
# PyTorch GPU
size = 1000
x = torch.rand(size=(size, size), dtype=torch.float32)
x = x.to("cuda")
%timeit x @ x.T

# 단위가 밀리초에서 마이크로초로 바뀌었음(빨라졌다는 의미입니다)

346 µs ± 113 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
